### PR TITLE
Revert "Upgrade google-protobuf to 3.15.0 (#452)"

### PR DESCRIPTION
**Pull request by qingling128**
This reverts commit 8e9c7963a18f3f5fdba9eb1f84960796d1deefcc.

The `google-protobuf` `3.15.0` version includes the segmentation fault fix, but introduced memory and cpu usage performance regression. Detailed reasons in b/181210044#comment7 and b/181210044#comment8. So we have to roll it back.

https://github.com/GoogleCloudPlatform/google-fluentd/pull/319 also rolls back https://github.com/GoogleCloudPlatform/google-fluentd/pull/318.

### CODE REVIEW

**Review by hsmatulisgoogle — COMMENTED** [review]
The changes look fine, but it looks like tests are failing? Seems unrelated
```
Error: test_autoformat_enabled_with_stackdriver_trace_id_as_trace(GoogleCloudOutputTest): NoMethodError: undefined method `each' for nil:NilClass
```

**Comment by qingling128** [comment]
I created a fake PR, and the tests are passing there: 
image

So the failed tests here are likely related to the `google-protobuf` change.

**Comment by qingling128** [comment]
The weird thing is that I can not reproduce the errors locally.

```
lingshi@lingshi:~/repo/fluent-plugin-google-cloud$ git branch
* lingshi-revert
  lingshi-test
  master

lingshi@lingshi:~/repo/fluent-plugin-google-cloud$ rake test
/usr/local/google/home/lingshi/.rvm/rubies/ruby-2.6.5/bin/ruby -I"lib:lib:test" -I"/usr/local/google/home/lingshi/.rvm/gems/ruby-2.6.5/gems/rake-10.5.0/lib" "/usr/local/google/home/lingshi/.rvm/gems/ruby-2.6.5/gems/rake-10.5.0/lib/rake/rake_test_loader.rb" "test/plugin/asserts.rb" "test/plugin/base_test.rb" "test/plugin/constants.rb" "test/plugin/test_driver.rb" "test/plugin/test_filter_add_insert_ids.rb" "test/plugin/test_filter_analyze_config.rb" "test/plugin/test_out_google_cloud.rb" "test/plugin/test_out_google_cloud_grpc.rb" "test/plugin/utils.rb"
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.
Loaded suite /usr/local/google/home/lingshi/.rvm/gems/ruby-2.6.5/gems/rake-10.5.0/lib/rake/rake_test_loader
Started
................................................................................................................................................................................................................................................
Finished in 337.547823956 seconds.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
240 tests, 36416 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
0.71 tests/s, 107.88 assertions/s
[Coveralls] Outside the CI environment, not sending data.
```

**Comment by qingling128** [comment]
Retried https://travis-ci.org/github/GoogleCloudPlatform/fluent-plugin-google-cloud/builds/763208928 and it's passing now.

Retrying https://travis-ci.org/github/GoogleCloudPlatform/fluent-plugin-google-cloud/builds/763208414 as well. If that one also passed, I'll merge this.

**Review by ekund — APPROVED** [review]

**Pull request merged**
