### PR TITLE
Set up coveralls for fluent-plugin-google-cloud test coverage analysis.

### PR DESCRIPTION
**Pull request by qingling128**

### CODE REVIEW

**Comment by qingling128** [comment]
Sample test coverage result:

image

**Comment by igorpeshansky** [comment]
Ooh, can we get this as a GitHub app?

**Comment by qingling128** [comment]
@igorpeshansky - GitHub app? It currently runs the test coverage number for each PR, and shows if a PR decreased the test coverage number. Is that what you meant?

**Comment by igorpeshansky** [comment]
Yes, that's what I meant. (edited the comment already).

**Pull request merged**
